config/routes.rb
Rails.application.routes.draw do
  resources :resumes do
    
  end
  get '/test_resume', to: 'resumes#test_resume', as: 'test_resume'
  root 'resumes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
class Resume < ApplicationRecord
  has_one_attached :file
  before_commit :read_pdf

  
  def read_pdf
    # byebug

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: %i[ show edit update destroy ]
  after_action :test_resume, only: %i[create]
  # GET /resumes or /resumes.json
  require 'prawn'
  require 'pdf/toolkit'
  require "origami"
  require 'prawn-styled-text'
  require 'barby'
  require 'barby/barcode/code_128'
  require 'barby/outputter/ascii_outputter'
  require 'barby/outputter/png_outputter'
  require 'open-uri'
  require 'chunky_png'

  def index
    @resumes = Resume.all
  end

  # GET /resumes/1 or /resumes/1.json

  def show
    # binding.pry
    active_storage_disk_service = ActiveStorage::Service::DiskService.new(root: Rails.root.to_s + '/storage/')
    path = active_storage_disk_service.send(:path_for, @resume.file.blob.key)
    my_pdf = PDF::Toolkit.open(path)
    @text = my_pdf.to_text.read.split(/\n+/)
    # binding.pry
    @barcode = Barby::Code128B.new(@text[20])
    @blob = Barby::PngOutputter.new(@barcode).to_png
    respond_to do |format|
      format.html
      format.png do
        send_data @blob, type: "image/png", disposition: "inline"
      end
    end

    # post.barcode.attach(blob)
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end
  def test_resume
    # binding.pry
    #  @a
    # template_filename = a["file"].path
    # binding.pry
    # my_pdf = PDF::Toolkit.open(template_filename)
    # @text = my_pdf.to_text.read.split(/\n+/)
  end


  # POST /resumes or /resumes.json
  def create
    @resume = Resume.new(resume_params)
    binding.pry
    @a = params[:resume]
    # test_resume(a)
    template_filename = @a["file"].path
    #       prawn_filename = 'temp.pdf'
    #       output_filename = 'output.pdf'
    #       Prawn::Document.generate(prawn_filename) do
    #         binding.pry

    #         # draw_text "Hello World", color: "red", :at => [100, 12]
    #          bounding_box([200,cursor], :width => 350, :height => 80) do
    #     stroke_bounds
    #     stroke do
    #         stroke_color 'FFFF00'
    #         fill_color '000000'
    #         fill_and_stroke_rounded_rectangle [cursor-80,cursor], 350, 80, 10
    #         fill_color '000000'
    #         text_box "Signature________", color: "FF6464", align: :right

    #     end
    # end
    #           puts page.text
          # end
          # my_pdf = PDF::Toolkit.open(template_filename)
          # text = my_pdf.to_text.read.split(/\n+/)
          # PDF::Toolkit.pdftk(prawn_filename, "background", template_filename, "output", output_filename)
    #       reader = PDF::Reader.new(pdf_path)
          # reader.pages.each do |page|
          #     reader.page.text.gsub('Download your free personal shopping assistant at meet.shop.app',a["dynamic_data"])
          #     puts page.text
          # end
    #       Prawn::Document.generate("hello.pdf") do
    #       reader.pages[6].text.gsub('Download your free personal shopping assistant at meet.shop.app',a["dynamic_data"])
    #       end

    respond_to do |format|
      if @resume.save
        format.html { redirect_to resume_url(@resume), notice: "Resume was successfully created." }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1 or /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to resume_url(@resume), notice: "Resume was successfully updated." }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1 or /resumes/1.json
  def destroy
    @resume.destroy

    respond_to do |format|
      format.html { redirect_to resumes_url, notice: "Resume was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resume_params
      params.require(:resume).permit(:name, :static_data, :dynamic_data, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PDF</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resumes/_form.html.erb
<%= form_with(model: resume) do |form| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
        <% resume.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="filed">
    <%= form.label :file %>
    <%= form.file_field :file, accept: 'text/pdf' %>
  </div>

  <div class="field">
    <%= form.label :static_data %>
    <%= form.text_field :static_data %>
  </div>

  <div class="field">
    <%= form.label :dynamic_data %>
    <%= form.text_field :dynamic_data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resumes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Static data</th>
      <th>Dynamic data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.name %></td>
        <td><%= resume.static_data %></td>
        <td><%= resume.dynamic_data %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/show.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dom-to-image/2.6.0/dom-to-image.min.js"
    integrity="sha256-c9vxcXyAG4paArQG3xk6DjyW/9aHxai2ef9RpMWO44A=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>

<style type="text/css"> * {margin:0; padding:0; text-indent:0; }
 .s1 { color: black; font-family:"Arial Black", sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 78pt; }
 .s2 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 8pt; }
 .s3 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 8pt; vertical-align: -4pt; }
 .s4 { color: black; font-family:"Arial Black", sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 20pt; }
 .s5 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 7pt; vertical-align: 1pt; }
 .s6 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 8pt; vertical-align: -3pt; }
 .s7 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 7pt; }
 .s8 { color: black; font-family:"Arial Black", sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 15pt; }
 .s9 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 7pt; }
 .s10 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 10pt; }
 .s11 { color: black; font-family:"Arial Black", sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 12pt; }
 .s12 { color: black; font-family:"Times New Roman", serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 10pt; }
 .s13 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 7pt; }
 table, tbody {vertical-align: top; overflow: visible; }
</style>
<div id="content" style="width: fit-content; padding: 30px;">
    <table style="border-collapse:collapse;" cellspacing="0" id="pdf_content">
        <tr style="height:71pt">
            <td style="width:72pt;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:1pt;border-right-style:solid;border-right-width:1pt">
              <p class="s1" style="padding-left: 11pt;text-indent: 0pt;line-height: 70pt;text-align: left;"><%= @text[0] %></p>
            </td>

            <td style="width:198pt;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:1pt;border-right-style:solid;border-right-width:1pt">
              <p style="text-indent: 0pt;text-align: left;"></p>
                <div style="padding: 12px; display: flex; padding-left: 64px; text-align: center;">
                  <p class="s2" style="padding-top: 38px;padding-right: 10px;"><%= @text[1] %></p>
                    <div style="padding: 9px;border: 2px solid;">
                      <p class="s2" style=""><%= @text[2] %></p>
                      <p class="s2" style=""><%= @text[3] %></p>
                      <p class="s2" style=""><%= @text[4] %></p>
                      <p class="s2" style=""><%= @text[5] %></p>
                    <div>
                </div>
            </td>
        </tr>
        <tr style="height:26pt">
            <td style="width:270pt;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:1pt;border-right-style:solid;border-right-width:1pt" colspan="2">
                <p class="s4" style="padding-left: 35pt;text-indent: 0pt;line-height: 25pt;text-align: left;"><%= @text[6] %></p>
            </td>
        </tr>
        <tr style="height:181pt">
            <td style="width:270pt;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:5pt;border-right-style:solid;border-right-width:1pt" colspan="2">
            <div style="display: flex; justify-content: space-between">
            <div>
                <p class="s2" style="padding-top: 4pt;padding-left: 4pt;text-indent: 0pt;line-height: 9pt;text-align: left;"><%= @text[7] %></p>
                <p class="s6" style="padding-left: 4pt;text-indent: 0pt;line-height: 10px;text-align: left;"><%= @text[8] %>
                <br><span class="s7"><%= @text[10] %></span></p>
                <p class="s2" style="padding-left: 4pt;text-indent: 0pt;text-align: left;"><%= @text[9] %></p></p>
              </div>
                 <div><span class="s5"><%= @text[11] %></span>
                  <p class="s2" style="text-indent: 0pt;line-height: 9pt;text-align: left;"><%= @text[12] %>
            </div>
              </div>
              <p class="s8" style="padding-right: 3pt;text-indent: 0pt;line-height: 21pt;text-align: right;"><%= @text[13] %></p>
                <p class="s9" style="padding-top: 4pt;padding-right: 3pt;text-indent: 0pt;text-align: right;"><%= @text[14] %></p>
                <p style="text-indent: 0pt;text-align: left;"><br/></p>
                <p class="s10" style="padding-top: 7pt;padding-left: 36pt;padding-right: 148pt;text-indent: 0pt;text-align: left;"><%= @text[15] %> <%= @text[16] %></p>
                <p class="s10" style="padding-left: 36pt;text-indent: 0pt;line-height: 12pt;text-align: left;"><%= @text[17] %></p>
                <p class="s10" style="padding-left: 36pt;text-indent: 0pt;line-height: 12pt;text-align: left;"><%= @text[18] %></p>
            </td>
            
        </tr>
        <tr style="height:104pt">
          <td style="width:270pt;border-top-style:solid;border-top-width:5pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:5pt;border-right-style:solid;border-right-width:1pt" colspan="2">
            <p class="s11" style="padding-left: 46pt;padding-right: 45pt;text-indent: 0pt;text-align: center; padding-top: 5px;"><%= @text[19] %></p>
            <p class="s12" style="display: flex; justify-content: center; text-indent: 0pt;text-align: left;"><%= image_tag(url_for({:controller => 'resumes', :action => 'show', :format => 'png' }),:class => "barcode" )%></p>
            <p class="s11" style="padding-top: 5pt;text-indent: 0pt;text-align: center; font-size: 15px;"><%= @text[20] %></p>
          </td>
        </tr>
        <tr style="height:21pt">
          <td style="width:270pt;border-top-style:solid;border-top-width:5pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:1pt;border-right-style:solid;border-right-width:1pt" colspan="2">
            <p class="s13" style="padding-top: 5pt;text-indent: 0pt;text-align: center; font-size: 11px; font-weight: 600">Download your free personal shopping assistant at me<u>et.shop  </u></p>
          </td>
        </tr>
      </table>
</div>
<button class="btn btn-info" id="downloadPDF">Download PDF</button>      

<script>
$('#downloadPDF').click(function () {
  debugger
    domtoimage.toPng(document.getElementById('content'))
        .then(function (blob) {
            var pdf = new jsPDF("p", "mm", "a4");

            pdf.addImage(blob, 'PNG', 0, 0, 210, 300);
            pdf.save("test.pdf");
        });
});
</script>

app/views/resumes/test_resume.html.erb
<style type="text/css"> * {margin:0; padding:0; text-indent:0; }
 .s1 { color: black; font-family:"Arial Black", sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 78pt; }
 .s2 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 8pt; }
 .s3 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 8pt; vertical-align: -4pt; }
 .s4 { color: black; font-family:"Arial Black", sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 20pt; }
 .s5 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 7pt; vertical-align: 1pt; }
 .s6 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 8pt; vertical-align: -3pt; }
 .s7 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 7pt; }
 .s8 { color: black; font-family:"Arial Black", sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 15pt; }
 .s9 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 7pt; }
 .s10 { color: black; font-family:Tahoma, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 10pt; }
 .s11 { color: black; font-family:"Arial Black", sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 12pt; }
 .s12 { color: black; font-family:"Times New Roman", serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 10pt; }
 .s13 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 7pt; }
 table, tbody {vertical-align: top; overflow: visible; }
</style>
<% binding.pry%>
    <p style="text-indent: 0pt;text-align: left;"><br/></p>
    <table style="border-collapse:collapse;margin-left:6pt" cellspacing="0">
        <tr style="height:71pt">
            <td style="width:72pt;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:1pt;border-right-style:solid;border-right-width:1pt">
                <p class="s1" style="padding-left: 11pt;text-indent: 0pt;line-height: 70pt;text-align: left;">P</p>
            </td>
            <td style="width:198pt;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:1pt;border-right-style:solid;border-right-width:1pt">
                <p style="text-indent: 0pt;text-align: left;">
                    <br/>
                </p>
                <p class="s2" style="padding-left: 43pt;padding-right: 14pt;text-indent: 58pt;line-height: 92%;text-align: left;">PRIORITY MAIL <span class="s3">CUBIC 0.10  </span>US POSTAGE PAID</p>
                <p class="s2" style="padding-left: 114pt;text-indent: 0pt;line-height: 4pt;text-align: left;">SHOPIFY</p>
                <p class="s2" style="padding-left: 110pt;text-indent: 0pt;line-height: 9pt;text-align: left;">ePOSTAGE</p>
            </td>
        </tr>
        <tr style="height:26pt">
            <td style="width:270pt;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:1pt;border-right-style:solid;border-right-width:1pt" colspan="2">
                <p class="s4" style="padding-left: 35pt;text-indent: 0pt;line-height: 25pt;text-align: left;">USPS PRIORITY MAIL</p>
            </td>
        </tr>
        <tr style="height:181pt">
            <td style="width:270pt;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:5pt;border-right-style:solid;border-right-width:1pt" colspan="2">
                <p class="s2" style="padding-top: 4pt;padding-left: 4pt;text-indent: 0pt;line-height: 9pt;text-align: left;">Element Brooklyn                     <span class="s5">10/05/22</span>
                </p>
                <p class="s6" style="padding-left: 4pt;text-indent: 0pt;line-height: 82%;text-align: left;">SUITE 311
                    <span class="s7">Mailed from 11206</span>
                </p>
                <p class="s2" style="padding-top: 2pt;padding-left: 4pt;text-indent: 0pt;text-align: left;">199 COOK ST</p>
                <p class="s2" style="padding-top: 1pt;padding-left: 4pt;text-indent: 0pt;line-height: 9pt;text-align: left;">BROOKLYN, NY 11206
                </p>
                <p class="s8" style="padding-right: 3pt;text-indent: 0pt;line-height: 21pt;text-align: right;">0020</p><p class="s9" style="padding-top: 4pt;padding-right: 3pt;text-indent: 0pt;text-align: right;">Order #23064</p><p style="text-indent: 0pt;text-align: left;"><br/></p><p class="s10" style="padding-top: 7pt;padding-left: 36pt;padding-right: 148pt;text-indent: 0pt;text-align: left;">Kevin Kovalesky D1</p><p class="s10" style="padding-left: 36pt;text-indent: 0pt;line-height: 12pt;text-align: left;">2079 31ST ST</p><p class="s10" style="padding-left: 36pt;text-indent: 0pt;line-height: 12pt;text-align: left;">ASTORIA, NY 11105-2560</p></td></tr><tr style="height:104pt"><td style="width:270pt;border-top-style:solid;border-top-width:5pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:5pt;border-right-style:solid;border-right-width:1pt" colspan="2"><p class="s11" style="padding-left: 46pt;padding-right: 45pt;text-indent: 0pt;text-align: center;">USPS TRACKING # - EP</p><p style="text-indent: 0pt;text-align: left;"><br/></p><p class="s12" style="padding-left: 15pt;text-indent: 0pt;text-align: left;"> </p><p class="s11" style="padding-top: 5pt;padding-left: 46pt;padding-right: 45pt;text-indent: 0pt;text-align: center;">9305 5109 4410 1582 0402 70</p></td></tr><tr style="height:21pt"><td style="width:270pt;border-top-style:solid;border-top-width:5pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:1pt;border-right-style:solid;border-right-width:1pt" colspan="2"><p style="text-indent: 0pt;text-align: left;"><br/></p><p class="s13" style="padding-left: 25pt;text-indent: 0pt;text-align: left;">Download your free personal shopping assistant at me<u>et.shop.app  </u></p></td></tr></table><p style="text-indent: 0pt;text-align: left;"/>